server:
  port: 8080
spring:
  application:
    name: start
  profiles:
    active: ${spring.profile:dev}
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      connection-test-query: select 1 from dual
      pool-name: HikariPool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  redis:
    timeout: 3000
    jedis:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 0
        max-wait: -1ms
logging:
  config: classpath:logback-spring.xml
jasypt:
  encryptor:
    password: Ryytn!123456
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    threadpool: fixed
    threads: 200
    # netty、netty3
    transporter: netty
    # HeaderExchanger
    exchanger: header
    # all、direct、message、connection、header
    dispatcher: message
  scan:
    base-packages: com.ryytn.start.service.entrance
  registry:
    id: ${spring.application.name}-registry
    address: nacos://${nacos.addr:127.0.0.1:8848}
    group: ${spring.application.name}
    username: ${nacos.username:nacos}
    password: ${nacos.password:nacos}
  consumer:
    check: false
    lazy: true